name: CI
on:
  pull_request:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node (runs only if package.json exists)
      - name: Setup Node
        if: hashFiles('package.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Node: install/lint/test
        if: hashFiles('package.json') != ''
        run: |
          npm ci
          npm run lint --if-present
          npm test --if-present -- --ci

      # Python (runs only if requirements.txt exists)
      - name: Setup Python
        if: hashFiles('requirements.txt') != ''
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Python: install/lint/test
        if: hashFiles('requirements.txt') != ''
        run: |
          pip install -r requirements.txt
          if command -v pytest; then pytest -q; fi
          if command -v flake8; then flake8 .; fi
